### ISSUE TITLE
Can't save as byte[]

### ISSUE THREAD

**Issue by unamed000** [MelbourneDeveloper/SQLite.Net-PCL#9]
Hi.

I've a model like this one:

    [Table("Ticket")]
    public class TicketDatabase : IIntIdEntity
    {
        [PrimaryKey]
        [AutoIncrement]
        public int DatabaseId { get; set; }

        public string Subject { get; set; }

        public string Body { get; set; }

        public byte[] LogsFile { get; set; }

    }

The problem is when i save the ticket database by using the package, the LogsFile will return null?

Any one have any idea about this issue?

Thanks

**Comment by moshiur** [comment]
I am having the same problem. Did anyone figure out a solution yet?

**Comment by MelbourneDeveloper** [comment]
I think you have the wrong repo. This repo doesn't have any ORM type functionality.
